[package]
name = "create-options-json"
version = "0.1.0"
edition = "2021"

[dependencies]
strip-ansi-escapes = "0.2.0"
colored = "1.0.0"
regex = "=0.2.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.0"